[general]
import = ["~/.config/alacritty/theme.toml"]

[window]
dynamic_padding = true
decorations = "None"

[scrolling]
history = 10000
multiplier = 3

[font]
normal.family = "FiraCode Nerd Font"
size = 11.0

[terminal]
shell.program = "zsh"

[keyboard]
bindings = [
	{ key = "W", mods = "Alt", action = "CreateNewWindow" },
	{ key = "Q", mods = "Alt", action = "Quit" },
	{ key = "C", mods = "Alt", action = "Copy" },
	{ key = "P", mods = "Alt", action = "Paste" },
]
